# setting for training UColor with Ranker loss

dataset:
    dataset_name : Dataset_Ucolor
    root : ../dataset/UIEB_all/Ucolor_npy
    crop_size: 128
    bs : 16
    num_workers : 2
    train_list_path : dataset/train_list.txt
    test_list_path : dataset/test_list.txt

model:
    model_name: UColor
    resume_ckpt_path:
    cuda: true
    parallel: true
    init_way:  # Gaussian initial distribution

train:
    # basic hyper parameters setting
    start_epoch: 0
    epoch: 1000
    lr: 1.0e-4
    optimizer: Adam
    lr_schedule: 
    lr_schedule_arg: 

    # loss setting
    loss_vgg: true
    loss_rank: true
    loss_coff: [1, 0.01, 0.01]

    ranker_args:
        model_name: MyCoaT
        resume_ckpt_path: ../myrank/checkpoints/MyCoaT/mycoatbest100.pth
        cuda: true
        parallel: false
        patch_size: 4
        embed_dims: [152, 320, 320, 320]
        serial_depths: [2, 2, 2, 2]
        parallel_depth: 6
        num_heads: 8
        mlp_ratios: [4, 4, 4, 4]
    
experiments:
    save_root: output/Ucolor/with_ranker_0.01_grad
    log: logs
    checkpoints: checkpoints
    results: results

test:
    start_epoch: 0
    end_epoch: 1
    test_ckpt_path:
    save_img: false