dataset:
    dataset_name : Dataset_Ranker
    root : ../dataset/UIERank
    bs : 1
    num_workers : 4
    train_list_path : dataset/ranker_train_list.txt
    test_list_path : dataset/ranker_test_list.txt

model:
    model_name: URanker
    resume_ckpt_path:
    cuda: true
    parallel: false
    patch_size: 4
    embed_dims: [152, 320, 320, 320]
    serial_depths: [2, 2, 2, 2]
    parallel_depth: 6
    num_heads: 8
    mlp_ratios: [4, 4, 4, 4]
    add_historgram: true
    his_channel: 192
    connect_type: dynamic

train:
    # basic hyper parameters setting
    start_epoch: 0
    epoch: 1000
    lr: 1.0e-5
    optimizer: Adam
    lr_schedule: 
    lr_schedule_arg: 
    
experiments:
    save_root: ranker_output/MyCoaT/dynamic
    log: logs
    checkpoints: checkpoints
    results: results

test:
    start_epoch: 0
    end_epoch: 1
    test_ckpt_path: